baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'Tech Scribe'

collections:
  team:
    output: true
    permalink: /about/:path/
  blog:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: 'images'
    values:
      image: true

sass:
  style: compact # possible values: nested expanded compact compressed

google_analytics_id: UA-170785184-1

plugins:
  - jekyll-environment-variables
